import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function openJournal(page,viewport){const root=viewport==='375px'?'.mobile-dock':'.desktop-rail';await page.locator(`${root} [data-view="reflect"]`).click();await page.locator('.reflect-view').waitFor({state:'visible'});await page.locator('[data-reflect-open-journal]').first().click();}
async function archivedEntry(page,body){const archive=page.locator('.journal-archive');await archive.waitFor({state:'visible'});if(!(await archive.evaluate(node=>node.open)))await archive.locator('summary').click();const entry=archive.locator('.journal-entry',{hasText:body});await entry.waitFor({state:'visible'});return entry;}
async function exercise(page,browserName,viewport){await page.addInitScript(()=>localStorage.setItem('growth-compass:preview2:e2:tutorial-state-v1','complete'));const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await openJournal(page,viewport);const view=page.locator('.journal-view');await view.waitFor({state:'visible'});assert.match(await view.innerText(),/Write first/);assert.equal(await page.locator('[data-return-parent="reflect"]').count(),1,`${browserName} ${viewport}: Journal must retain a clear return to Reflect`);await page.locator('[data-journal-new]').click();const dialog=page.locator('[data-journal-dialog]');await dialog.waitFor({state:'visible'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('journal-modal-open')),true,`${browserName} ${viewport}: Journal editor must lock background scroll`);assert.ok(await dialog.getByText(/Saving one does not create Progress/).isVisible());const body=`A factual private reflection for ${browserName} ${viewport}.`;await dialog.locator('textarea[name="body"]').fill(body);await dialog.locator('button[type="submit"]').click();await dialog.waitFor({state:'detached'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('journal-modal-open')),false,`${browserName} ${viewport}: Journal editor must release background scroll`);let entry=page.locator('.journal-entry',{hasText:body}).filter({has:page.locator('[data-journal-archive]')});await entry.waitFor({state:'visible'});const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Journal must not overflow horizontally; ${JSON.stringify(size)}`);

await entry.locator('[data-journal-archive]').click();await entry.waitFor({state:'detached'});let archived=await archivedEntry(page,body);assert.match(await archived.innerText(),/Restore/);await archived.locator('[data-journal-restore]').click();await archived.waitFor({state:'detached'});entry=page.locator('.journal-entry',{hasText:body}).filter({has:page.locator('[data-journal-archive]')});await entry.waitFor({state:'visible'});

await entry.locator('[data-journal-archive]').click();await entry.waitFor({state:'detached'});archived=await archivedEntry(page,body);const removeButton=archived.locator('[data-journal-remove]');await removeButton.focus();await removeButton.click();const removeDialog=page.locator('.journal-delete-dialog');await removeDialog.waitFor({state:'visible'});assert.equal(await removeDialog.getAttribute('role'),'dialog');assert.match(await removeDialog.innerText(),/cannot be undone/i);assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('journal-modal-open')),true);await page.keyboard.press('Escape');await removeDialog.waitFor({state:'detached'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('journal-modal-open')),false);assert.equal(await removeButton.evaluate(node=>document.activeElement===node),true,`${browserName} ${viewport}: closing permanent-removal dialog must restore focus`);await removeButton.click();await page.locator('.journal-delete-dialog').waitFor({state:'visible'});await page.locator('[data-journal-remove-confirm]').click();await page.locator('.journal-delete-dialog').waitFor({state:'detached'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('journal-modal-open')),false);await archived.waitFor({state:'detached'});}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Journal archive lifecycle under Reflect`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Journal archive lifecycle under Reflect`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
