import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function openSettings(page,viewport){if(viewport==='375px'){await page.locator('#mobileExploreToggle').click();const nav=page.locator('#mobileSecondary [data-view="settings"]');await nav.waitFor({state:'visible'});await nav.click();return;}await page.locator('.desktop-rail [data-view="settings"]').click();}
async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await openSettings(page,viewport);const view=page.locator('.settings-view');await view.waitFor({state:'visible'});const settingsText=await view.innerText();assert.match(settingsText,/Appearance/);assert.match(settingsText,/Your data/);assert.match(settingsText,/Export my data/);assert.match(settingsText,/Download a copy of your Growth Compass information/);assert.match(settingsText,/Product tour/);assert.match(settingsText,/Open full tutorial/);assert.doesNotMatch(settingsText,/Preview 2 only|debug|developer|cache|reset preferences/i,`${browserName} ${viewport}: product Settings must not expose Preview/debug/cache/developer controls`);assert.equal(await page.locator('#clearE2Cache,#resetE2Preferences,#e2PaletteSwitcher').count(),0);
  const downloadPromise=page.waitForEvent('download');await page.locator('#exportE2Data').click();const download=await downloadPromise;assert.match(download.suggestedFilename(),/^growth-compass-data-\d{4}-\d{2}-\d{2}\.json$/);await page.waitForFunction(()=>document.querySelector('#exportDataStatus')?.textContent?.includes('ready'),undefined,{timeout:5_000});const exportResponse=await page.request.get(new URL('/api/export',BASE_URL).toString());assert.equal(exportResponse.ok(),true);const exportBody=await exportResponse.json();assert.equal(exportBody.schema_version,1);assert.ok(exportBody.profile,`${browserName} ${viewport}: export must contain the current profile`);assert.ok(exportBody.version_one,`${browserName} ${viewport}: export must contain profile-scoped version-one data`);
  await page.locator('#replayE2Tutorial').click();let tutorial=page.locator('.gc-tutorial-card');await tutorial.waitFor({state:'visible'});assert.match(await tutorial.innerText(),/A quick tour/);assert.match(await tutorial.innerText(),/Skip tutorial/);await tutorial.locator('[data-tutorial-next]').click();await page.waitForTimeout(120);tutorial=page.locator('.gc-tutorial-card');assert.match(await tutorial.innerText(),/Today/);assert.ok(await page.locator('.gc-tutorial-target').count()>=1,`${browserName} ${viewport}: tutorial must highlight a real shell target`);await tutorial.locator('[data-tutorial-skip]').click();await tutorial.waitFor({state:'detached'});await page.locator('#replayE2Tutorial').click();tutorial=page.locator('.gc-tutorial-card');await tutorial.waitFor({state:'visible'});await page.keyboard.press('Escape');await tutorial.waitFor({state:'detached'});
  await page.locator('input[name="e2-theme"][value="light"]').check();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('meta[name="theme-color"]').getAttribute('content'),'#f3f0e8');await page.reload({waitUntil:'domcontentloaded'});await page.locator('.settings-view').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('input[name="e2-motion"][value="reduce"]').check();assert.equal(await page.locator('html').getAttribute('data-motion'),'reduce');const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Settings must not overflow horizontally; ${JSON.stringify(size)}`);}
for(const [browserName,browserType]of BROWSERS){test(`${browserName} desktop accepts Experience 2 Settings, export and tutorial`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Settings, export and tutorial`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,acceptDownloads:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
