import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
const PREFIX='growth-compass:preview2:e2:';

async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await page.locator('[data-view="settings"]:visible').first().click();const view=page.locator('.settings-view');await view.waitFor({state:'visible'});assert.match(await view.innerText(),/Preview 2 only/);await page.locator('input[name="e2-theme"][value="light"]').check();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('meta[name="theme-color"]').getAttribute('content'),'#f3f4f7');await page.reload({waitUntil:'domcontentloaded'});await page.locator('.settings-view').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('input[name="e2-motion"][value="reduce"]').check();assert.equal(await page.locator('html').getAttribute('data-motion'),'reduce');await page.evaluate(async()=>{await caches.open('growth-compass-preview2-e2-browser-sentinel');await caches.open('growth-compass-unrelated-browser-sentinel')});await page.locator('#clearE2Cache').click();await page.waitForFunction(()=>document.querySelector('#cacheResetStatus')?.textContent?.startsWith('Cleared '),undefined,{timeout:5_000});const cacheState=await page.evaluate(async()=>{const names=await caches.keys();return{owned:names.includes('growth-compass-preview2-e2-browser-sentinel'),unrelated:names.includes('growth-compass-unrelated-browser-sentinel')}});assert.equal(cacheState.owned,false);assert.equal(cacheState.unrelated,true);await page.evaluate(()=>caches.delete('growth-compass-unrelated-browser-sentinel'));await page.locator('#resetE2Preferences').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('html').getAttribute('data-motion'),null);const preferenceCount=await page.evaluate(prefix=>Object.keys(localStorage).filter(key=>key.startsWith(prefix)).length,PREFIX);assert.equal(preferenceCount,0);const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Settings must not overflow horizontally; ${JSON.stringify(size)}`);}

for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Settings isolation`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Settings isolation`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
