import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
const PREFIX='growth-compass:preview2:e2:';
async function openSettings(page,viewport){if(viewport==='375px'){await page.locator('#mobileExploreToggle').click();const nav=page.locator('#mobileSecondary [data-view="settings"]');await nav.waitFor({state:'visible'});await nav.click();return;}await page.locator('.desktop-rail [data-view="settings"]').click();}
async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await openSettings(page,viewport);const view=page.locator('.settings-view');await view.waitFor({state:'visible'});const settingsText=await view.innerText();assert.match(settingsText,/Preview 2 only/);assert.match(settingsText,/Appearance/);assert.match(settingsText,/Interactive tutorial/);assert.match(settingsText,/Replay tutorial/);assert.equal(await page.locator('#e2PaletteSwitcher').count(),0,`${browserName} ${viewport}: retired Ambient Luxury palette gallery must not remain mounted`);
  await page.locator('#replayE2Tutorial').click();let tutorial=page.locator('.gc-tutorial-card');await tutorial.waitFor({state:'visible'});assert.match(await tutorial.innerText(),/A quick tour/);assert.match(await tutorial.innerText(),/Skip tutorial/);await tutorial.locator('[data-tutorial-next]').click();await page.waitForTimeout(120);tutorial=page.locator('.gc-tutorial-card');assert.match(await tutorial.innerText(),/Today/);assert.ok(await page.locator('.gc-tutorial-target').count()>=1,`${browserName} ${viewport}: tutorial must highlight a real shell target`);await tutorial.locator('[data-tutorial-skip]').click();await tutorial.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>localStorage.getItem('growth-compass:preview2:e2:tutorial-state-v1')),'skipped');await page.locator('#replayE2Tutorial').click();tutorial=page.locator('.gc-tutorial-card');await tutorial.waitFor({state:'visible'});await page.keyboard.press('Escape');await tutorial.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>localStorage.getItem('growth-compass:preview2:e2:tutorial-state-v1')),'skipped');
  await page.locator('input[name="e2-theme"][value="light"]').check();assert.equal(await page.locator('html').getAttribute('data-theme'),'light');assert.equal(await page.locator('meta[name="theme-color"]').getAttribute('content'),'#f3f0e8');await page.reload({waitUntil:'domcontentloaded'});await page.locator('.settings-view').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');await page.locator('input[name="e2-motion"][value="reduce"]').check();assert.equal(await page.locator('html').getAttribute('data-motion'),'reduce');await page.evaluate(async()=>{await caches.open('growth-compass-preview2-e2-browser-sentinel');await caches.open('growth-compass-unrelated-browser-sentinel')});await page.locator('#clearE2Cache').click();await page.waitForFunction(()=>document.querySelector('#cacheResetStatus')?.textContent?.startsWith('Cleared '),undefined,{timeout:5_000});const cacheState=await page.evaluate(async()=>{const names=await caches.keys();return{owned:names.includes('growth-compass-preview2-e2-browser-sentinel'),unrelated:names.includes('growth-compass-unrelated-browser-sentinel')}});assert.equal(cacheState.owned,false);assert.equal(cacheState.unrelated,true);await page.evaluate(()=>caches.delete('growth-compass-unrelated-browser-sentinel'));await page.locator('#resetE2Preferences').click();assert.equal(await page.locator('html').getAttribute('data-theme'),'dark');assert.equal(await page.locator('html').getAttribute('data-motion'),null);const preferenceCount=await page.evaluate(prefix=>Object.keys(localStorage).filter(key=>key.startsWith(prefix)).length,PREFIX);assert.equal(preferenceCount,0);const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Settings must not overflow horizontally; ${JSON.stringify(size)}`);}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Settings and tutorial isolation`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Settings and tutorial isolation`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
