import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const SCREENSHOT_DIR=process.env.GC_E2E_SCREENSHOT_DIR||'';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function capture(page,browserName,viewport,state){if(!SCREENSHOT_DIR||browserName!=='Chromium')return;await mkdir(SCREENSHOT_DIR,{recursive:true});await page.waitForTimeout(160);await page.screenshot({path:`${SCREENSHOT_DIR}/e2-first-run-growth-${viewport}-${state}.png`,fullPage:false,animations:'disabled'});}
async function assertNoOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: first-run Today must not overflow horizontally; ${JSON.stringify(size)}`);}
async function waitForFirstDirectionWrite(state,label){const deadline=Date.now()+10_000;while(Date.now()<deadline){if(state.areas.length===1&&state.goals.length===1)return;await new Promise(resolve=>setTimeout(resolve,50));}assert.fail(`${label}: first direction write did not reach mocked Areas and Goals contracts`);}
async function mockNewAccount(page){const goals=[],areas=[];await page.route('**/api/v1/areas*',async route=>{const request=route.request();if(request.method()==='POST'){const body=request.postDataJSON(),area={id:501,name:body.name,status:'active',template_key:body.template_key??null,sort_order:body.sort_order??100};areas.push(area);await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({item:area})});return;}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:areas})});});await page.route('**/api/v1/goals*',async route=>{const request=route.request();if(request.method()==='POST'){const body=request.postDataJSON(),area=areas.find(candidate=>Number(candidate.id)===Number(body.area_id)),goal={id:901,name:body.name,status:'active',area_id:body.area_id??null,area_name:area?.name??null,measurement_type:body.measurement_type,target_period:body.target_period,target_value:body.target_value??null,minimum_value:body.minimum_value??null,unit:body.unit??null,why_text:body.why_text??null};goals.splice(0,goals.length,goal);await route.fulfill({status:201,contentType:'application/json',body:JSON.stringify({item:goal})});return;}await route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:goals})});});await page.route('**/api/v1/capacity/commitments*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}));await page.route('**/api/v1/capacity/summary*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({flexible_minutes:10080,planned_goal_minutes:0,committed_minutes:0,overcommitted_minutes:0,goals:[],commitments:[]})}));await page.route('**/api/v1/daily-plan*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({items:[]})}));await page.route('**/api/v1/today*',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({progress:[],direction:[]})}));return{goals,areas};}
async function exercise(page,browserName,viewport){
  if(viewport==='375px')await page.addInitScript(()=>localStorage.setItem('growth-compass:preview2:e2:theme','light'));
  const state=await mockNewAccount(page);const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());assert.equal(await page.locator('html').getAttribute('data-theme'),viewport==='375px'?'light':'dark');
  const welcome=page.locator('.today-first-run');await welcome.waitFor({state:'visible',timeout:15_000});await page.getByRole('heading',{name:'What would make the next year meaningfully better?'}).waitFor({state:'visible'});assert.equal(await page.getByRole('button',{name:'Choose what matters'}).count(),1);assert.equal(await page.locator('.today-onboarding-step').count(),0,`${browserName} ${viewport}: first-run should not teach the architecture with four expandable steps`);assert.equal(await page.locator('.onboarding-compass-line').count(),1);assert.match(await welcome.innerText(),/Start with one part of life/);assert.doesNotMatch(await welcome.innerText(),/How your compass grows|Direction guides the Plan|Actions create Progress/);await assertNoOverflow(page,`${browserName} ${viewport}`);await capture(page,browserName,viewport,'welcome');
  await page.getByRole('button',{name:'Choose what matters'}).click();const dialog=page.getByRole('dialog',{name:'Where do you want to grow first?'});await dialog.waitFor({state:'visible'});assert.equal(await dialog.getByText('Time spent').count(),0);await dialog.locator('input[name="todayFirstArea"][value="career"]').check({force:true});await page.locator('#todayFirstGoalName').fill('Build a meaningful first direction');await page.locator('#todayFirstGoalWhy').fill('It gives the rest of the system a reason to exist.');await capture(page,browserName,viewport,'direction');await dialog.getByRole('button',{name:'Set my direction'}).click();
  await waitForFirstDirectionWrite(state,`${browserName} ${viewport}`);assert.equal(state.areas.length,1);assert.equal(state.goals[0].measurement_type,'milestone');assert.equal(state.goals[0].target_period,'none');
  await page.reload({waitUntil:'domcontentloaded',timeout:15_000});const guided=page.locator('.today-compass-ready');await guided.waitFor({state:'visible',timeout:15_000});await page.getByRole('heading',{name:'Make one part of the direction real.'}).waitFor({state:'visible'});assert.match(await guided.innerText(),/career/i);assert.match(await guided.innerText(),/Build a meaningful first direction/);assert.match(await guided.innerText(),/How predictable is your week\?/);assert.equal(await page.locator('.today-onboarding-step').count(),0);assert.doesNotMatch(await guided.innerText(),/Direction tells Plan what matters|Direction[\s\S]*Plan[\s\S]*Action[\s\S]*Progress/);await assertNoOverflow(page,`${browserName} ${viewport} guided`);await capture(page,browserName,viewport,'guided');
  await page.getByRole('button',{name:/My week changes a lot/i}).click();await page.locator('.plan-view').waitFor({state:'visible',timeout:15_000});assert.equal(await page.locator('#viewTitle').innerText(),'Planning details');assert.equal(await page.locator('[data-return-parent="compass"]').count(),1,`${browserName} ${viewport}: first-run planning must land inside the Compass hierarchy`);
}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts progressive Experience 2 first-run`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts progressive Experience 2 first-run`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
