import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function noOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: must not overflow horizontally; ${JSON.stringify(size)}`);}
async function exercise(page,browserName,viewport){
  const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await page.locator('#viewHost').waitFor({state:'visible'});
  const primary=viewport==='375px'?page.locator('.mobile-dock [data-primary-nav]'):page.locator('.desktop-rail [data-primary-nav]');assert.equal(await primary.count(),4,`${browserName} ${viewport}: primary navigation must expose four growth destinations`);
  assert.equal(await page.locator('.mobile-dock [data-view="plan"]').count(),0);assert.equal(await page.locator('.mobile-dock [data-view="progress"]').count(),0);assert.equal(await page.locator('.mobile-dock [data-view="wellness"]').count(),0);
  await page.locator('.today-glance').waitFor({state:'visible'});assert.equal(await page.locator('.gc-today-focus').count(),1,`${browserName} ${viewport}: Today must have one dominant focus object`);assert.equal(await page.locator('.gc-today-vitals>div').count(),3);assert.equal(await page.locator('.today-open-day:visible').count(),0,`${browserName} ${viewport}: empty Today must not repeat itself in a second giant card`);await noOverflow(page,`${browserName} ${viewport} Today`);
  if(viewport==='375px'){const header=await page.locator('.mobile-header').boundingBox();const dock=await page.locator('.mobile-dock').boundingBox();assert.ok(header&&header.height<=64,`${browserName}: mobile chrome must leave room for content`);assert.ok(dock&&dock.height<=70,`${browserName}: mobile dock must stay compact`);}
  await primary.filter({hasText:'Compass'}).click();await page.locator('.compass-view').waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Compass');assert.equal(await page.locator('.gc-path').count(),1,`${browserName} ${viewport}: Compass must connect real direction to week and today`);assert.equal(await page.locator('.compass-capacity-ring').count(),0,`${browserName} ${viewport}: retired decorative capacity ring must not return`);const setup=await page.locator('.gc-capacity-setup').count();if(setup)assert.equal((await page.locator('.gc-capacity-setup').innerText()).includes('168h'),false,`${browserName} ${viewport}: unset routine must not present all 168 weekly hours as usable capacity`);await noOverflow(page,`${browserName} ${viewport} Compass`);
  await primary.filter({hasText:'Patterns'}).click();await page.locator('.patterns-view').waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Patterns');const baseline=await page.locator('.gc-baseline-card').count();if(baseline){assert.equal(await page.locator('.gc-energy-chart').count(),0,`${browserName} ${viewport}: baseline state must not render empty analytics`);assert.equal(await page.locator('.gc-week-bars').count(),0,`${browserName} ${viewport}: baseline state must progressively disclose later evidence views`);assert.match(await page.locator('.patterns-view').innerText(),/baseline|ordinary days|tracked/i);}else{assert.ok(await page.locator('.gc-pattern-block').count()>=1,`${browserName} ${viewport}: evidence-rich state must show real pattern blocks`);}assert.equal(await page.locator('.evidence-orbit').count(),0,`${browserName} ${viewport}: decorative evidence orbit must remain retired`);await noOverflow(page,`${browserName} ${viewport} Patterns`);
  await primary.filter({hasText:'Reflect'}).click();await page.locator('.reflect-view').waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Reflect');assert.equal(await page.locator('.gc-period-switch').count(),1);assert.equal(await page.locator('[data-reflect-panel]:visible').count(),1,`${browserName} ${viewport}: Reflect must reconstruct one period at a time`);assert.equal(await page.locator('.reflect-review-card').count(),0,`${browserName} ${viewport}: two giant report cards must not return`);await page.locator('[data-reflect-period="monthly"]').click();assert.equal(await page.locator('[data-reflect-panel="monthly"]:visible').count(),1);await noOverflow(page,`${browserName} ${viewport} Reflect`);
  const add=viewport==='375px'?page.locator('.mobile-dock [data-open-add]'):page.locator('.desktop-rail [data-open-add]');await add.click();const hub=page.getByRole('dialog',{name:'What do you want to do?'});await hub.waitFor({state:'visible'});assert.equal(await hub.locator('[data-add-intent]').count(),5);const descriptionBox=await hub.locator('[data-add-intent] span').first().boundingBox();assert.ok(!descriptionBox||descriptionBox.width<=2,`${browserName} ${viewport}: Add descriptions should remain accessible without becoming visible reading work`);await hub.locator('[data-add-intent="in_progress"]').click();const logger=page.getByRole('dialog',{name:'Add activity'});await logger.waitFor({state:'visible'});assert.equal(await logger.locator('input[name="loggerEntryMode"][value="in_progress"]').isChecked(),true);await page.keyboard.press('Escape');
}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts 90-bar Growth Compass composition`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts 90-bar Growth Compass composition`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
