import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const API_BASE=new URL('/api/v1/',BASE_URL).toString();
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
function todayKey(){const now=new Date();const offset=now.getTimezoneOffset()*60000;return new Date(now.getTime()-offset).toISOString().slice(0,10);}
async function createRunning(page,title){const response=await page.request.post(`${API_BASE}daily-plan`,{data:{planned_for:todayKey(),title,status:'in_progress',source:'manual'}});assert.ok(response.ok(),`creating running Today item failed: ${response.status()} ${await response.text()}`);return (await response.json()).item;}
async function dismiss(page,id){const response=await page.request.put(`${API_BASE}daily-plan/${id}`,{data:{status:'dismissed'}});assert.ok(response.ok(),`cleaning running Today item failed: ${response.status()} ${await response.text()}`);}
async function exercise(page,browserName,viewport){const firstTitle=`Running A ${browserName} ${viewport}`,secondTitle=`Running B ${browserName} ${viewport}`;const first=await createRunning(page,firstTitle),second=await createRunning(page,secondTitle);try{const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok(),`${browserName} ${viewport}: Experience 2 must load`);const now=page.locator('.today-now');await now.waitFor({state:'visible'});await now.getByText(firstTitle,{exact:true}).waitFor({state:'visible'});await now.getByText(secondTitle,{exact:true}).waitFor({state:'visible'});assert.equal(await now.locator('.today-now-also').isVisible(),true,`${browserName} ${viewport}: additional running intentions must stay visible`);assert.match(await now.locator('.today-now-also-head').innerText(),/Also in progress/i);assert.equal(await now.locator('[data-today-done]').count()>=2,true,`${browserName} ${viewport}: every running item must remain actionable`);const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Today must not overflow horizontally; ${JSON.stringify(size)}`);}finally{await dismiss(page,first.id);await dismiss(page,second.id);}}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop keeps every running Experience 2 Today item visible`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px keeps every running Experience 2 Today item visible`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
