import test from 'node:test';
import assert from 'node:assert/strict';
import { webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const UA='Mozilla/5.0 (iPhone; CPU iPhone OS 18_6 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/18.6 Mobile/15E148 Safari/604.1';

async function context(browser){return browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,userAgent:UA});}

test('WebKit iPhone accepts isolated Experience 2 install guidance',async()=>{const browser=await webkit.launch();try{const ctx=await context(browser);const page=await ctx.newPage();const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());const banner=page.locator('.install-app-banner');await banner.waitFor({state:'visible',timeout:4_000});assert.match(await banner.innerText(),/Install Growth Compass/);const overflow=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(overflow.document<=overflow.viewport+1,`iPhone install banner must not overflow: ${JSON.stringify(overflow)}`);const install=banner.locator('[data-install-help]');await install.focus();await install.click();const dialog=page.locator('.install-help-card');await dialog.waitFor({state:'visible'});await page.waitForFunction(()=>document.querySelector('#experience2App')?.inert===true);assert.match(await dialog.innerText(),/Share[\s\S]*Add to Home Screen[\s\S]*Open as Web App/);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});await page.waitForFunction(()=>document.querySelector('#experience2App')?.inert===false);assert.equal(await install.evaluate(node=>document.activeElement===node),true,'closing install help must restore focus to Install');await banner.locator('[data-install-later]').click();await banner.waitFor({state:'detached'});const dismissed=await page.evaluate(()=>Number(localStorage.getItem('growth-compass:preview2:e2:ios-install-later')||0));assert.ok(dismissed>0,'Later must store only the isolated Experience 2 dismissal timestamp');await ctx.close();}finally{await browser.close();}});

test('WebKit iPhone standalone mode suppresses install guidance',async()=>{const browser=await webkit.launch();try{const ctx=await context(browser);const page=await ctx.newPage();await page.addInitScript(()=>Object.defineProperty(navigator,'standalone',{configurable:true,value:true}));const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await page.waitForTimeout(900);assert.equal(await page.locator('.install-app-banner').count(),0);await ctx.close();}finally{await browser.close();}});
