import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function openInsights(page,viewport){if(viewport==='375px'){await page.locator('#mobileExploreToggle').click();const nav=page.locator('#mobileSecondary [data-view="insights"]');await nav.waitFor({state:'visible'});await nav.click();return;}await page.locator('.desktop-rail [data-view="insights"]').click();}
async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await openInsights(page,viewport);const view=page.locator('.insights-view');await view.waitFor({state:'visible'});const text=await view.innerText();assert.match(text,/Association is never presented as cause/);assert.match(text,/Paired days/);assert.match(text,/No defensible matched pattern yet/);const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${browserName} ${viewport}: Insights must not overflow horizontally; ${JSON.stringify(size)}`);const summary=page.locator('.insights-method summary');await summary.waitFor({state:'visible'});await summary.focus();assert.equal(await summary.evaluate(node=>document.activeElement===node),true,`${browserName} ${viewport}: Insights method disclosure must be keyboard focusable`);await page.keyboard.press('Enter');await page.locator('.insight-stage-grid').waitFor({state:'visible'});}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Insights`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Insights`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
