import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function noOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: must not overflow horizontally; ${JSON.stringify(size)}`);}
async function exercise(page,browserName,viewport){
  const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await page.locator('#viewHost').waitFor({state:'visible'});
  const primary=viewport==='375px'?page.locator('.mobile-dock [data-primary-nav]'):page.locator('.desktop-rail [data-primary-nav]');assert.equal(await primary.count(),4,`${browserName} ${viewport}: primary navigation must expose four growth questions`);
  assert.equal(await page.locator('.mobile-dock [data-view="plan"]').count(),0);assert.equal(await page.locator('.mobile-dock [data-view="progress"]').count(),0);assert.equal(await page.locator('.mobile-dock [data-view="wellness"]').count(),0);
  const surface=page.locator('.static-surface').first();if(await surface.count()){const visual=await surface.evaluate(node=>({backdrop:getComputedStyle(node).backdropFilter,shadow:getComputedStyle(node).boxShadow}));assert.ok(!visual.backdrop||visual.backdrop==='none',`${browserName} ${viewport}: core surfaces must not use glass blur`);}
  await primary.filter({hasText:'Compass'}).click();await page.getByRole('heading',{name:'Where are you going?'}).waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Compass');assert.equal(await page.locator('.compass-line').count(),1);await noOverflow(page,`${browserName} ${viewport} Compass`);
  await primary.filter({hasText:'Patterns'}).click();await page.getByRole('heading',{name:'What is your life showing you?'}).waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Patterns');assert.equal(await page.locator('.evidence-stage').count(),1);assert.match(await page.locator('.patterns-view').innerText(),/not explanations|does not prove cause|descriptions/i);await noOverflow(page,`${browserName} ${viewport} Patterns`);
  await primary.filter({hasText:'Reflect'}).click();await page.getByRole('heading',{name:'What have you learned?'}).waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Reflect');assert.equal(await page.locator('[data-reflect-review="weekly"]').count(),1);assert.equal(await page.locator('[data-reflect-review="monthly"]').count(),1);await noOverflow(page,`${browserName} ${viewport} Reflect`);
  const add=viewport==='375px'?page.locator('.mobile-dock [data-open-add]'):page.locator('.desktop-rail [data-open-add]');await add.click();const hub=page.getByRole('dialog',{name:'What do you want to do?'});await hub.waitFor({state:'visible'});assert.equal(await hub.locator('[data-add-intent]').count(),5);await hub.locator('[data-add-intent="in_progress"]').click();const logger=page.getByRole('dialog',{name:'Add activity'});await logger.waitFor({state:'visible'});assert.equal(await logger.locator('input[name="loggerEntryMode"][value="in_progress"]').isChecked(),true,`${browserName} ${viewport}: Do something now must create in-progress intention, not factual Progress`);await page.keyboard.press('Escape');
}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Growth Compass four-question composition`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Growth Compass four-question composition`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
