import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function assertNoOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: Goals must not overflow horizontally; ${JSON.stringify(size)}`);}
async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());const goalsNav=page.locator('[data-view="goals"]:visible').first();await goalsNav.waitFor({state:'visible'});await goalsNav.click();await page.locator('.goals-view').waitFor({state:'visible'});await assertNoOverflow(page,`${browserName} ${viewport}`);let add=page.locator('[data-goal-new]').first();await add.focus();await add.click();let dialog=page.locator('.goal-editor');await dialog.waitFor({state:'visible'});assert.equal(await dialog.getAttribute('role'),'dialog');assert.equal(await page.locator('input[name="goalMeasure"]').count(),4);await page.locator('label.goal-measure:has(input[value="boolean"])').click();assert.equal(await page.locator('.goal-target').isVisible(),false,`${browserName} ${viewport}: Completed goals must not force numeric targets`);await page.locator('label.goal-measure:has(input[value="time"])').click();assert.equal(await page.locator('.goal-target').isVisible(),true,`${browserName} ${viewport}: Time goals may expose optional numeric guidance`);await assertNoOverflow(page,`${browserName} ${viewport} dialog`);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});assert.equal(await add.evaluate(node=>document.activeElement===node),true,`${browserName} ${viewport}: closing editor must restore focus`);
  await page.evaluate(()=>localStorage.setItem('growth-compass:preview2:e2:theme','light'));await page.reload({waitUntil:'domcontentloaded'});await page.locator('.goals-view').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light',`${browserName} ${viewport}: light preference must apply`);add=page.locator('[data-goal-new]').first();await add.click();dialog=page.locator('.goal-editor');await dialog.waitFor({state:'visible'});const themeColors=await dialog.evaluate(node=>{const style=getComputedStyle(node),root=getComputedStyle(document.documentElement);return{background:style.backgroundColor,text:style.color,surface:root.getPropertyValue('--gc-surface').trim(),semanticText:root.getPropertyValue('--gc-text').trim(),resolvedSurface:getComputedStyle(document.body.appendChild(Object.assign(document.createElement('i'),{style:'display:none;background:var(--gc-surface);color:var(--gc-text)'}))).backgroundColor};});const expected=await page.evaluate(()=>{const probe=document.createElement('i');probe.style.cssText='position:fixed;visibility:hidden;background:var(--gc-surface);color:var(--gc-text)';document.body.appendChild(probe);const style=getComputedStyle(probe),result={background:style.backgroundColor,text:style.color};probe.remove();return result;});assert.equal(themeColors.background,expected.background,`${browserName} ${viewport}: Goal editor must use light semantic surface`);assert.equal(themeColors.text,expected.text,`${browserName} ${viewport}: Goal editor text must use light semantic text`);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});
  const name=`Browser goal ${browserName} ${viewport}`;await add.click();await page.locator('#goalName').fill(name);await page.locator('#goalForm button[type="submit"]').click();await page.locator('.goal-editor').waitFor({state:'detached'});const card=page.locator('.goal-card',{hasText:name});await card.waitFor({state:'visible'});const archive=card.locator('[data-goal-archive]');await archive.focus();await archive.click();const archiveDialog=page.locator('.goal-archive-dialog');await archiveDialog.waitFor({state:'visible'});assert.equal(await archiveDialog.getAttribute('role'),'dialog');await assertNoOverflow(page,`${browserName} ${viewport} archive dialog`);await page.keyboard.press('Escape');await archiveDialog.waitFor({state:'detached'});assert.equal(await archive.evaluate(node=>document.activeElement===node),true,`${browserName} ${viewport}: closing archive dialog must restore focus`);await archive.click();await page.locator('.goal-archive-dialog').waitFor({state:'visible'});await page.locator('[data-goal-archive-confirm]').click();await page.locator('.goal-archive-dialog').waitFor({state:'detached'});await card.waitFor({state:'detached'});}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Goals`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Goals`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
