import test from 'node:test';
import assert from 'node:assert/strict';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
async function assertNoOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: Activities must not overflow horizontally; ${JSON.stringify(size)}`);}
async function seed(page,label){return page.evaluate(async label=>{const request=async(path,options={})=>{const response=await fetch(`/api${path}`,{headers:{'Content-Type':'application/json'},...options});const body=await response.json();if(!response.ok)throw new Error(body.error||`HTTP ${response.status}`);return body;};const goal=(await request('/v1/goals',{method:'POST',body:JSON.stringify({name:`Activity browser Goal ${label}`})})).item;const activity=(await request('/v1/activities',{method:'POST',body:JSON.stringify({name:`Initial Activity ${label}`,goal_id:goal.id,description:'Browser seed'})})).item;return{goal,activity};},label)}
async function openActivities(page,viewport){if(viewport==='375px'){const explore=page.locator('#mobileExploreToggle');await explore.click();const nav=page.locator('#mobileSecondary [data-view="activities"]');await nav.waitFor({state:'visible'});await nav.click();return;}await page.locator('.desktop-rail [data-view="activities"]').click();}
async function exercise(page,browserName,viewport){const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());const token=`${browserName}-${viewport}-${Date.now()}-${Math.random().toString(16).slice(2)}`;const seeded=await seed(page,token);await openActivities(page,viewport);await page.locator('.activities-view').waitFor({state:'visible'});await assertNoOverflow(page,`${browserName} ${viewport}`);const row=page.locator(`[data-activity-id="${seeded.activity.id}"]`);await row.waitFor({state:'visible'});assert.match(await row.textContent(),/Initial Activity/);const edit=row.locator('[data-activity-edit]');await edit.focus();await edit.click();const dialog=page.locator('.activity-editor');await dialog.waitFor({state:'visible'});assert.equal(await dialog.getAttribute('role'),'dialog');assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('activity-modal-open')),true,`${browserName} ${viewport}: Activity dialog must lock background scroll`);const editedName=`Edited Activity ${token}`;const name=page.locator('#activityName');await name.fill(editedName);await page.locator('#activityDescription').fill('Edited through Experience 2');await page.locator('#activityEditorForm button[type="submit"]').click();await dialog.waitFor({state:'detached'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('activity-modal-open')),false,`${browserName} ${viewport}: Activity dialog must release background scroll`);const editedRow=page.locator(`[data-activity-id="${seeded.activity.id}"]`,{hasText:editedName});await editedRow.waitFor({state:'visible'});assert.match(await editedRow.textContent(),/Edited Activity/);await assertNoOverflow(page,`${browserName} ${viewport} edited`);const archive=editedRow.locator('[data-activity-archive]');await archive.click();const archiveDialog=page.locator('.activity-archive-dialog');await archiveDialog.waitFor({state:'visible'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('activity-modal-open')),true);assert.match(await archiveDialog.textContent(),/Existing factual Progress remains unchanged/);await page.locator('#activityArchiveConfirm').click();await archiveDialog.waitFor({state:'detached'});assert.equal(await page.locator('body').evaluate(node=>node.classList.contains('activity-modal-open')),false);await page.locator(`[data-activity-id="${seeded.activity.id}"]`).waitFor({state:'detached'});}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Activities CRUD`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900}});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Activities CRUD`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
