import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const SCREENSHOT_DIR=process.env.GC_E2E_SCREENSHOT_DIR||'';
async function capture(page,viewport,state){if(!SCREENSHOT_DIR)return;await mkdir(SCREENSHOT_DIR,{recursive:true});await page.waitForTimeout(180);await page.screenshot({path:`${SCREENSHOT_DIR}/e2-growth-${viewport}-${state}.png`,fullPage:false,animations:'disabled'});}
async function assertNoOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: Experience 2 must not overflow horizontally; ${JSON.stringify(size)}`);}
async function primary(page,view,viewport){const root=viewport==='mobile'?'.mobile-dock':'.desktop-rail';await page.locator(`${root} [data-view="${view}"]`).click();await page.locator(`.${view}-view`).waitFor({state:'visible',timeout:15_000});await assertNoOverflow(page,`${viewport} ${view}`);}
async function more(page,view,viewport){if(viewport==='mobile'){const toggle=page.locator('#mobileExploreToggle');if(await toggle.getAttribute('aria-expanded')!=='true')await toggle.click();await page.locator(`#mobileSecondary [data-view="${view}"]`).click();}else await page.locator(`.desktop-rail [data-view="${view}"]`).click();await page.locator(`.${view}-view`).waitFor({state:'visible',timeout:15_000});await assertNoOverflow(page,`${viewport} ${view}`);}
async function evidence(viewport,contextOptions){const browser=await chromium.launch();try{const context=await browser.newContext(contextOptions);const page=await context.newPage();const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await page.locator('.today-view').waitFor({state:'visible',timeout:15_000});await capture(page,viewport,'today');
  await primary(page,'compass',viewport);await capture(page,viewport,'compass');await page.locator('[data-compass-open="goals"]').first().click();await page.locator('.direction-view').waitFor({state:'visible'});await capture(page,viewport,'direction');await page.locator('[data-return-parent="compass"]').click();await page.locator('.compass-view').waitFor({state:'visible'});await page.locator('[data-compass-open="plan"]').click();await page.locator('.plan-view').waitFor({state:'visible'});await capture(page,viewport,'planning-details');await page.locator('[data-plan-open="schedule"]').first().click();await page.locator('.schedule-view').waitFor({state:'visible'});await capture(page,viewport,'routine');
  await primary(page,'patterns',viewport);await capture(page,viewport,'patterns');await page.locator('[data-patterns-open="progress"]').click();await page.locator('.progress-view').waitFor({state:'visible'});await capture(page,viewport,'factual-progress');await page.locator('[data-return-parent="patterns"]').click();await page.locator('.patterns-view').waitFor({state:'visible'});await page.locator('[data-patterns-open="insights"]').click();await page.locator('.insights-view').waitFor({state:'visible'});await capture(page,viewport,'evidence-details');
  await primary(page,'reflect',viewport);await capture(page,viewport,'reflect');await page.locator('[data-reflect-review="weekly"]').click();await page.locator('.reflect-dialog').waitFor({state:'visible'});await capture(page,viewport,'weekly-review');await page.keyboard.press('Escape');
  await more(page,'activities',viewport);await capture(page,viewport,'activities');await more(page,'wellness',viewport);await capture(page,viewport,'wellness');await more(page,'settings',viewport);await capture(page,viewport,'settings');
  await primary(page,'today',viewport);await page.locator('[data-open-add]:visible').first().click();await page.locator('#addHub').waitFor({state:'visible'});await capture(page,viewport,'add-intent');await page.locator('[data-add-intent="planned"]').click();await page.locator('.logger-panel').waitFor({state:'visible'});await capture(page,viewport,'add-planned');await page.keyboard.press('Escape');await context.close();}finally{await browser.close();}}

test('Chromium desktop captures Growth Compass composition evidence',async()=>{await evidence('desktop',{viewport:{width:1280,height:900},reducedMotion:'reduce'});});
test('Chromium 375px captures Growth Compass composition evidence',async()=>{await evidence('mobile',{viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});});
