import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
import { chromium, webkit } from 'playwright';

const BASE_URL=process.env.GC_E2E_BASE_URL||'http://127.0.0.1:8787/experience/2/';
const SCREENSHOT_DIR=process.env.GC_E2E_SCREENSHOT_DIR||'';
const BROWSERS=[['Chromium',chromium],['WebKit',webkit]];
const STARTER_AREA_KEYS=['career','health','learning','finance','relationships','personal','custom'];
async function capture(page,browserName,viewport,state){if(!SCREENSHOT_DIR||browserName!=='Chromium')return;await mkdir(SCREENSHOT_DIR,{recursive:true});await page.waitForTimeout(120);await page.screenshot({path:`${SCREENSHOT_DIR}/e2-direction-chromium-${viewport}-${state}.png`,fullPage:false,animations:'disabled'});}
async function assertNoOverflow(page,label){const size=await page.evaluate(()=>({viewport:document.documentElement.clientWidth,document:document.documentElement.scrollWidth}));assert.ok(size.document<=size.viewport+1,`${label}: Direction must not overflow horizontally; ${JSON.stringify(size)}`);}
async function openDirection(page,viewport){const root=viewport==='375px'?'.mobile-dock':'.desktop-rail';await page.locator(`${root} [data-view="compass"]`).click();await page.locator('.compass-view').waitFor({state:'visible'});await page.locator('[data-compass-open="goals"]').first().click();}
async function exercise(page,browserName,viewport){
  const response=await page.goto(BASE_URL,{waitUntil:'domcontentloaded',timeout:15_000});assert.ok(response?.ok());await openDirection(page,viewport);
  const direction=page.locator('.direction-view');await direction.waitFor({state:'visible'});await page.getByRole('heading',{name:'Where do you want to go?'}).waitFor({state:'visible'});assert.equal(await page.locator('#viewTitle').innerText(),'Direction');assert.match(await page.title(),/^Direction — Growth Compass$/);assert.equal(await page.locator('[data-return-parent="compass"]').count(),1,`${browserName} ${viewport}: Direction must remain visibly subordinate to Compass`);await assertNoOverflow(page,`${browserName} ${viewport} direction page`);await capture(page,browserName,viewport,'page');
  let add=page.locator('[data-goal-new]').first();await add.focus();await add.click();let dialog=page.getByRole('dialog',{name:'Where do you want to move?'});await dialog.waitFor({state:'visible'});assert.match(await dialog.innerText(),/Three small decisions\. Details can wait\./i);const areaInputs=dialog.locator('input[name="directionArea"]');assert.ok(await areaInputs.count()>=STARTER_AREA_KEYS.length);for(const key of STARTER_AREA_KEYS)assert.equal(await dialog.locator(`input[name="directionArea"][value="${key}"]`).count(),1);assert.equal(await dialog.locator('input[name="goalMeasure"]').count(),0,`${browserName} ${viewport}: simple Direction creation must defer tracking administration`);await page.keyboard.press('Escape');await dialog.waitFor({state:'detached'});assert.equal(await add.evaluate(node=>document.activeElement===node),true,`${browserName} ${viewport}: closing Direction creation must restore focus`);
  const name=`Direction ${browserName} ${viewport} ${Date.now()}`;add=page.locator('[data-goal-new]').first();await add.click();dialog=page.getByRole('dialog',{name:'Where do you want to move?'});await dialog.waitFor({state:'visible'});await dialog.locator('input[name="directionArea"][value="career"]').check({force:true});await dialog.locator('#directionName').fill(name);await dialog.locator('#directionWhy').fill('This makes future choices easier.');await dialog.getByRole('button',{name:'Create direction'}).click();const success=page.getByRole('dialog',{name:"You know where you're moving."});await success.waitFor({state:'visible',timeout:15_000});assert.match(await success.innerText(),/career/i);assert.match(await success.innerText(),new RegExp(name));assert.match(await success.innerText(),/Plan my first step/i);assert.match(await success.innerText(),/Add tracking details/i);await capture(page,browserName,viewport,'success');
  await success.getByRole('button',{name:'Add tracking details'}).click();const advanced=page.getByRole('dialog',{name:'Keep it useful'});await advanced.waitFor({state:'visible'});const tracking=advanced.locator('.goal-tracking-options');assert.equal(await tracking.getAttribute('open'),null);await tracking.locator('summary').click();assert.equal(await advanced.locator('input[name="goalMeasure"]').count(),4);await page.keyboard.press('Escape');await advanced.waitFor({state:'detached'});
  const card=page.locator('.goal-card',{hasText:name});await card.waitFor({state:'visible'});assert.match(await card.innerText(),/career/i);assert.match(await card.innerText(),/This makes future choices easier\./i);assert.match(await card.innerText(),/Plan next step/i);await card.locator('[data-goal-open]').click();const detail=page.getByRole('dialog',{name});await detail.waitFor({state:'visible'});assert.match(await detail.innerText(),/why this matters/i);assert.match(await detail.innerText(),/next useful move/i);await detail.getByRole('button',{name:'Archive'}).click();const archiveDialog=page.locator('.goal-archive-dialog');await archiveDialog.waitFor({state:'visible'});assert.match(await archiveDialog.innerText(),/archive direction/i);await page.locator('[data-goal-archive-confirm]').click();await card.waitFor({state:'detached',timeout:15_000});
  await page.evaluate(()=>localStorage.setItem('growth-compass:preview2:e2:theme','light'));await page.reload({waitUntil:'domcontentloaded'});await page.locator('.direction-view').waitFor({state:'visible'});assert.equal(await page.locator('html').getAttribute('data-theme'),'light');add=page.locator('[data-goal-new]').first();await add.click();dialog=page.getByRole('dialog',{name:'Where do you want to move?'});await dialog.waitFor({state:'visible'});const themeColors=await dialog.evaluate(node=>{const style=getComputedStyle(node);return{background:style.backgroundColor,text:style.color};});const expected=await page.evaluate(()=>{const probe=document.createElement('i');probe.style.cssText='position:fixed;visibility:hidden;background:var(--gc-surface);color:var(--gc-text)';document.body.appendChild(probe);const style=getComputedStyle(probe),result={background:style.backgroundColor,text:style.color};probe.remove();return result;});assert.equal(themeColors.background,expected.background);assert.equal(themeColors.text,expected.text);await page.keyboard.press('Escape');await assertNoOverflow(page,`${browserName} ${viewport} light direction`);
}
for(const [browserName,browserType] of BROWSERS){test(`${browserName} desktop accepts Experience 2 Direction under Compass`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:1280,height:900},reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'desktop');await context.close();}finally{await browser.close();}});test(`${browserName} 375px accepts Experience 2 Direction under Compass`,async()=>{const browser=await browserType.launch();try{const context=await browser.newContext({viewport:{width:375,height:812},isMobile:true,hasTouch:true,reducedMotion:'reduce'});await exercise(await context.newPage(),browserName,'375px');await context.close();}finally{await browser.close();}});}
