import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const quality = await readFile(new URL('../.github/workflows/quality.yml', import.meta.url), 'utf8');
const packageJson = JSON.parse(await readFile(new URL('../package.json', import.meta.url), 'utf8'));
const browserTest = await readFile(new URL('./browser/browser-e2e.browser.js', import.meta.url), 'utf8');
const recoveryBrowserTest = await readFile(new URL('./browser/functional-recovery.browser.js', import.meta.url), 'utf8');
const breathingVisualTest = await readFile(new URL('./browser/breathing-visual.browser.js', import.meta.url), 'utf8');
const goalsBrowserTest = await readFile(new URL('./browser/experience2-goals.browser.js', import.meta.url), 'utf8');
const journalBrowserTest = await readFile(new URL('./browser/experience2-journal.browser.js', import.meta.url), 'utf8');
const liveSessionBrowserTest = await readFile(new URL('./browser/experience2-live-session.browser.js', import.meta.url), 'utf8');
const runner = await readFile(new URL('../scripts/run-browser-e2e.sh', import.meta.url), 'utf8');

const browserCommand = 'node --test --test-concurrency=1 tests/browser/browser-e2e.browser.js tests/browser/functional-recovery.browser.js tests/browser/breathing-visual.browser.js';

test('Quality keeps pinned Chromium and WebKit browser acceptance release-blocking', () => { assert.equal(packageJson.devDependencies.playwright,'1.62.0');assert.equal(packageJson.scripts['test:browser'],browserCommand);assert.match(quality,/playwright@1\.62\.0/);assert.match(quality,/playwright install --with-deps chromium webkit/);assert.match(quality,/bash scripts\/run-browser-e2e\.sh/);assert.ok(quality.indexOf('npm run test:integration')<quality.indexOf('run-browser-e2e.sh')); });
test('browser acceptance runs only against an isolated local Worker and local D1', () => { assert.match(runner,/d1 migrations apply DB/);assert.match(runner,/--local/);assert.match(runner,/--persist-to/);assert.match(runner,/wrangler dev/);assert.match(runner,/127\.0\.0\.1:8787\/api\/health/);assert.match(runner,/GC_E2E_BASE_URL=http:\/\/127\.0\.0\.1:8787/);assert.match(runner,/run_e2_suite\(\)/);assert.match(runner,/node --test "\$file"/);assert.match(runner,/tests\/browser\/experience2-logger\.browser\.js/);assert.match(runner,/assert_worker_alive/);assert.doesNotMatch(runner,/--remote|workers\.dev|1937971c|a182d8c8/); });
test('Experience 2 browser suites release engine resources between files and keep visual evidence last',()=>{assert.match(runner,/fresh Node process/);assert.match(runner,/for suite in/);assert.ok(runner.indexOf('tests/browser/experience2-wellness.browser.js')<runner.indexOf('tests/browser/experience2-visual.browser.js'));assert.match(runner,/cat "\$WORKER_LOG"/);});
test('state-heavy Direction Journal and live-session acceptance runs every engine and viewport in isolated Worker cases',()=>{assert.match(runner,/run_e2_state_matrix\(\)/);for(const caseName of ['chromium-desktop','chromium-375','webkit-desktop','webkit-375'])assert.ok(runner.includes(caseName),`${caseName} must be an isolated state-heavy browser case`);for(const path of ['tests/browser/experience2-goals.browser.js','tests/browser/experience2-journal.browser.js','tests/browser/experience2-live-session.browser.js'])assert.ok(runner.includes(path),`${path} must use the state-heavy matrix`);for(const source of [goalsBrowserTest,journalBrowserTest,liveSessionBrowserTest]){assert.match(source,/GC_E2E_CASE/);assert.match(source,/shouldRun/);assert.match(source,/Chromium/);assert.match(source,/WebKit/);assert.match(source,/375px/);}});
test('live-session browser cases retain enough time for slower WebKit completion without dropping assertions',()=>{assert.match(liveSessionBrowserTest,/CASE_TIMEOUT_MS=60_000/);assert.match(liveSessionBrowserTest,/\{timeout:CASE_TIMEOUT_MS\}/);assert.match(liveSessionBrowserTest,/live-session Done must create factual Progress exactly once/);assert.match(liveSessionBrowserTest,/completed session must leave the active Daily Plan list/);});
test('browser acceptance proves Product Rebuild workflows across desktop and 375px Chromium/WebKit', () => { assert.match(browserTest,/chromium/);assert.match(browserTest,/webkit/);assert.match(browserTest,/width:\s*375,\s*height:\s*812/);assert.match(browserTest,/product-rebuild\.css/);assert.match(browserTest,/product-rebuild-pages\.css/);assert.match(browserTest,/gc-today-rebuild/);assert.match(browserTest,/gc-add-activity-sheet/);assert.match(browserTest,/gc-plan-rebuild/);assert.match(browserTest,/gc-progress-rebuild/);assert.match(browserTest,/gc-insights-rebuild/);assert.match(browserTest,/#topMore > summary/);assert.match(browserTest,/must not overflow horizontally/);assert.doesNotMatch(browserTest,/preview-empty\.css|blank canvas/);assert.doesNotMatch(browserTest,/https:\/\//); });
test('browser acceptance explicitly covers recovered Add Today Tomorrow and Schedule behavior', () => { assert.match(recoveryBrowserTest,/chromium/);assert.match(recoveryBrowserTest,/webkit/);assert.match(recoveryBrowserTest,/value="done"/);assert.match(recoveryBrowserTest,/gc-tomorrow-plan/);assert.match(recoveryBrowserTest,/gc-plan-working/);assert.match(recoveryBrowserTest,/commitmentEditor/);assert.match(recoveryBrowserTest,/plan-loading/);assert.doesNotMatch(recoveryBrowserTest,/https:\/\//); });
test('browser acceptance measures visible breathing expansion and contraction in both engines', () => { assert.match(breathingVisualTest,/chromium/);assert.match(breathingVisualTest,/webkit/);assert.match(breathingVisualTest,/inhaleMid/);assert.match(breathingVisualTest,/exhaleMid/);assert.match(breathingVisualTest,/open\/closed contrast must be unmistakable/);assert.doesNotMatch(breathingVisualTest,/https:\/\//); });
