import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { canTransitionDailyPlanStatus, normalizeDailyPlanInput } from '../worker/modules/daily-plan/domain.js';
const migration=await readFile(new URL('../migrations/0004_daily_plan.sql',import.meta.url),'utf8');
const data=await readFile(new URL('../worker/modules/daily-plan/data.js',import.meta.url),'utf8');
const workerModule=await readFile(new URL('../worker/modules/daily-plan/module.js',import.meta.url),'utf8');
const frontendModule=await readFile(new URL('../public/js/modules/daily-plan/module.js',import.meta.url),'utf8');
const logger=await readFile(new URL('../public/js/features/logger.js',import.meta.url),'utf8');

test('Daily Plan accepts a simple title-only Today or Tomorrow intention',()=>{const a=normalizeDailyPlanInput({planned_for:'2026-08-13',title:'Prepare clothes for the gym'});assert.equal(a.error,undefined);assert.equal(a.value.planned_minutes,null);assert.equal(a.value.activity_key,null);const b=normalizeDailyPlanInput({planned_for:'2026-08-14',title:'Back workout',planned_time:'07:30',planned_minutes:60});assert.equal(b.error,undefined);assert.equal(b.value.planned_for,'2026-08-14');assert.equal(b.value.planned_minutes,60)});
test('Daily Plan validation rejects malformed dates time and duration',()=>{assert.match(normalizeDailyPlanInput({planned_for:'2026-02-30',title:'x'}).error,/valid plan date/);assert.match(normalizeDailyPlanInput({planned_for:'2026-08-14',title:'x',planned_time:'29:00'}).error,/HH:MM/);assert.match(normalizeDailyPlanInput({planned_for:'2026-08-14',title:'x',planned_minutes:0}).error,/1–1440/)});
test('Daily Plan lifecycle is explicit',()=>{assert.equal(canTransitionDailyPlanStatus('planned','in_progress'),true);assert.equal(canTransitionDailyPlanStatus('planned','completed'),true);assert.equal(canTransitionDailyPlanStatus('in_progress','completed'),true);assert.equal(canTransitionDailyPlanStatus('completed','planned'),false)});
test('Daily Plan persistence is date-exact and separate from Progress',()=>{assert.match(migration,/CREATE TABLE IF NOT EXISTS daily_plan_items/);assert.doesNotMatch(migration,/CREATE TABLE.*progress_records/is);assert.match(data,/WHERE profile_id=\? AND planned_for=\?/);assert.doesNotMatch(data,/planned_for\s*<=\?|overdue|carry.?forward/i)});
test('Daily Plan is an isolated registered module',()=>{assert.match(workerModule,/id: 'daily-plan'/);assert.match(workerModule,/\/api\/v1\/daily-plan/);assert.match(frontendModule,/id: 'daily-plan'/);assert.match(frontendModule,/Today & tomorrow/);assert.doesNotMatch(frontendModule,/features\/today\.js|features\/logger\.js/)});
test('Planning through Logger returns before canonical completed Progress write',()=>{const planBranch=logger.indexOf("if (entryMode === 'planned' || entryMode === 'in_progress')");const onIntent=logger.indexOf('await onIntent?.(',planBranch);const branchReturn=logger.indexOf('return;',onIntent);const progressWrite=logger.indexOf("api('/api/v1/progress'",planBranch);assert.ok(planBranch>=0);assert.ok(onIntent>planBranch);assert.ok(branchReturn>onIntent);assert.ok(progressWrite>branchReturn);assert.doesNotMatch(logger,/api\(['"]\/api\/session/);assert.match(logger,/Doing now must use Today/);assert.match(logger,/focus, variation, subtask/i)});
test('Daily Plan UI explicitly avoids automatic catch-up semantics',()=>{assert.match(frontendModule,/Unfinished items do not become debt tomorrow/);assert.match(frontendModule,/never roll into the next day automatically/);assert.doesNotMatch(frontendModule,/automatically.*tomorrow|carry.*forward|overdue.*today/i)});
