import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const app=await readFile(new URL('../public/experience/2/js/app.js',import.meta.url),'utf8');
const view=await readFile(new URL('../public/experience/2/js/views/activities.js',import.meta.url),'utf8');
const capability=await readFile(new URL('../public/experience/2/js/capabilities/activities.js',import.meta.url),'utf8');
const goalsCapability=await readFile(new URL('../public/experience/2/js/capabilities/goals.js',import.meta.url),'utf8');
const routes=await readFile(new URL('../worker/modules/activities/routes.js',import.meta.url),'utf8');
const moduleSource=await readFile(new URL('../worker/modules/activities/module.js',import.meta.url),'utf8');
const plan=await readFile(new URL('../public/experience/2/js/views/plan.js',import.meta.url),'utf8');
const css=await readFile(new URL('../public/experience/2/css/activities.css',import.meta.url),'utf8');
const lifecycleCss=await readFile(new URL('../public/experience/2/css/lifecycle.css',import.meta.url),'utf8');
const index=await readFile(new URL('../public/experience/2/index.html',import.meta.url),'utf8');
const sw=await readFile(new URL('../public/experience/2/sw.js',import.meta.url),'utf8');

test('Experience 2 Activities is a real canonical lifecycle management surface',()=>{assert.match(app,/loadActivities\s*,\s*renderActivities\s*,\s*bindActivities/);assert.match(app,/current==='activities'/);assert.match(view,/activitiesCapability\.list\(\{includeArchived:true\}\)/);assert.match(view,/goalsCapability\.references\(\{includeArchived:true\}\)/);assert.doesNotMatch(view,/goalsCapability\.load\(/);assert.match(goalsCapability,/async references\(\{includeArchived=false\}=\{\}\)/);assert.match(capability,/api\.get\(`\/v1\/activities\$\{query\?/);assert.doesNotMatch(view,/renderFoundation|\/v1\/activities|\bapi\./);});
test('Activity lifecycle reloads avoid dragging unrelated Area data through the Goal capability',()=>{assert.match(view,/const items=await activitiesCapability\.list\(\{includeArchived:true\}\);const goals=await goalsCapability\.references\(\{includeArchived:true\}\)/);assert.doesNotMatch(view,/Promise\.all/);assert.match(goalsCapability,/references[\s\S]*api\.get\(`\/v1\/goals\$\{goalQuery\(includeArchived\)\}`\)/);});
test('Experience 2 Activities keeps archive restore and permanent removal behind its public capability',()=>{for(const call of [/activitiesCapability\.create\(payload\)/,/activitiesCapability\.update\(item\.id,payload\)/,/activitiesCapability\.archive\(item\.id\)/,/activitiesCapability\.restore\(item\.id\)/,/activitiesCapability\.remove\(item\.id\)/])assert.match(view,call);assert.match(capability,/api\.delete\(activityPath\(id\)\)/);assert.match(capability,/api\.post\(`\$\{activityPath\(id\)\}\/restore`,\{\}\)/);assert.match(capability,/api\.delete\(`\$\{activityPath\(id\)\}\/permanent`\)/);assert.ok(moduleSource.includes('\\/restore$/')&&moduleSource.includes('handler: restoreActivityRoute'),'restore route must remain explicitly registered');assert.ok(moduleSource.includes('\\/permanent$/')&&moduleSource.includes('handler: removeActivityRoute'),'permanent removal route must remain explicitly registered');assert.match(routes,/Restore the parent Direction before restoring this Activity/);assert.doesNotMatch(view,/progressCapability|\/v1\/progress/);});
test('Activity management preserves Plan versus factual Progress semantics',()=>{assert.match(view,/planning structure, not evidence of completion/i);assert.match(view,/Archive is reversible\. Remove is permanent\./);assert.match(view,/Existing factual Progress remains unchanged/);assert.match(view,/Existing factual Progress remains, but its direct Activity link may be cleared/);assert.doesNotMatch(view,/mark complete|completed automatically|catch.?up|streak debt/i);});
test('Activities editor and lifecycle confirmation are keyboard-modal safe',()=>{assert.match(view,/role="dialog" aria-modal="true" aria-labelledby="activityEditorTitle"/);assert.match(view,/role="dialog" aria-modal="true" aria-labelledby="activityLifecycleTitle"/);assert.match(view,/event\.key==='Escape'/);assert.match(view,/event\.key!=='Tab'/);assert.match(view,/document\.body\.classList\.add\('activity-modal-open'\)/);assert.match(view,/document\.body\.classList\.remove\('activity-modal-open'\)/);assert.match(view,/previousFocus\?\.focus\?\.\(\{preventScroll:true\}\)/);assert.doesNotMatch(view,/window\.confirm|confirm\(/);assert.match(css,/\.activity-modal-open\{overflow:hidden\}/);assert.match(css,/@media\(max-width:760px\)/);assert.match(css,/env\(safe-area-inset-bottom\)/);assert.match(css,/\.activity-editor-close\{width:48px;height:48px/);assert.match(lifecycleCss,/\.danger-button/);assert.match(lifecycleCss,/@media\(max-width:620px\)/);});
test('Plan and shell expose Activities without changing the five-item mobile dock',()=>{assert.match(plan,/data-plan-open="activities"/);assert.match(plan,/navigate\?\.\(button\.dataset\.planOpen\)/);assert.match(index,/desktop-rail[\s\S]*data-view="activities"/);assert.match(index,/mobile-secondary[\s\S]*data-view="activities"/);const dock=index.match(/<nav class="mobile-dock"[\s\S]*?<\/nav>/)?.[0]||'';assert.equal((dock.match(/data-view=/g)||[]).length,4);assert.equal((dock.match(/data-open-add/g)||[]).length,1);assert.doesNotMatch(dock,/data-view="activities"/);});
test('Experience 2 PWA precaches Activities and lifecycle assets in its isolated refreshed cache',()=>{assert.match(sw,/growth-compass-preview2-e2-v\d+/);for(const asset of ['/experience/2/css/activities.css','/experience/2/css/lifecycle.css','/experience/2/js/views/activities.js','/experience/2/js/capabilities/activities.js'])assert.ok(sw.includes(`'${asset}'`),`${asset} must be precached`);assert.doesNotMatch(sw,/growth-compass-preview1|experience\/1/);});