import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const root=process.cwd();
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const sha1=body=>crypto.createHash('sha1').update(body).digest('hex');
function gitObjectSha(type,body){const data=Buffer.isBuffer(body)?body:Buffer.from(body);return sha1(Buffer.concat([Buffer.from(`${type} ${data.length}\0`),data]));}
function gitBlobSha(file){return gitObjectSha('blob',fs.readFileSync(path.join(root,file)));}
function gitTreeSha(relativeDir){const absolute=path.join(root,relativeDir);const entries=fs.readdirSync(absolute,{withFileTypes:true}).map(entry=>{const rel=path.join(relativeDir,entry.name);if(entry.isDirectory())return{name:entry.name,sort:`${entry.name}/`,mode:'40000',sha:gitTreeSha(rel)};const stat=fs.statSync(path.join(root,rel));return{name:entry.name,sort:entry.name,mode:(stat.mode&0o111)?'100755':'100644',sha:gitBlobSha(rel)}}).sort((a,b)=>Buffer.compare(Buffer.from(a.sort),Buffer.from(b.sort)));const chunks=[];for(const entry of entries)chunks.push(Buffer.from(`${entry.mode} ${entry.name}\0`),Buffer.from(entry.sha,'hex'));return gitObjectSha('tree',Buffer.concat(chunks));}
function*walk(dir){for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const file=path.join(dir,entry.name);if(entry.isDirectory())yield*walk(file);else yield file}}

test('selector exposes exactly the two Preview 2 experiences',()=>{const html=read('public/selector/index.html');assert.match(html,/href="\/experience\/1\/"/);assert.match(html,/Experience 1/);assert.match(html,/Current \/ Recovered/);assert.match(html,/href="\/experience\/2\/"/);assert.match(html,/Experience 2/);assert.match(html,/New \/ Ambient Luxury/);assert.doesNotMatch(html,/\/js\/app\.js/);const worker=read('worker/index.js');assert.match(worker,/url\.pathname === '\/'/);assert.match(worker,/\/selector\/index\.html/);});

test('Wrangler runs the Worker before selector and Experience 1 adapter routes',()=>{const config=JSON.parse(read('wrangler.jsonc'));const routes=config.assets?.run_worker_first;assert.ok(Array.isArray(routes));for(const route of ['/api/*','/','/index.html','/experience/1','/experience/1/*'])assert.ok(routes.includes(route),`Missing Worker-first route ${route}`);assert.equal(routes.includes('/experience/2/*'),false);});

test('Experience 1 recovered frontend remains byte-frozen',()=>{assert.equal(gitBlobSha('public/index.html'),'6769ddad7631970a5670f55e5262cb7f0d839946');assert.equal(gitBlobSha('public/experience/1/index.html'),'6769ddad7631970a5670f55e5262cb7f0d839946');assert.equal(gitBlobSha('public/styles.css'),'39c3f743bb2362f6bee8b9f39d3658f55a39638c');assert.equal(gitTreeSha('public/css'),'e82da9897aeac9be2d8ff5c59060a6a6ff52a743');assert.equal(gitTreeSha('public/fonts'),'79f5d7e5586aa9beaa2d951ef101cd2bb86ae2c6');assert.equal(gitTreeSha('public/js'),'04955551a39623b97bde7c458c8e00e9e4d47f65');assert.equal(gitBlobSha('public/icon.svg'),'a7237c74710736bd9934f659b3e07724de832576');assert.equal(gitBlobSha('public/manifest.webmanifest'),'5f587f3f0792089511484c33d0c7c74e15b6c3e0');assert.match(read('docs/PREVIEW2_MASTER_HANDOFF.md'),/3cf2a65b5918f73e4f182abfdce8589c98d85277/);});

test('Experience frontends do not import sibling frontend resources',()=>{const sources1=[path.join(root,'public','experience','1'),path.join(root,'public','css'),path.join(root,'public','js')];const sources2=[path.join(root,'public','experience','2')];for(const [sources,sibling]of [[sources1,'2'],[sources2,'1']])for(const dir of sources)for(const file of walk(dir)){if(!/\.(?:html|css|js|mjs)$/.test(file))continue;const source=fs.readFileSync(file,'utf8');const pattern=new RegExp(`(?:from\\s*|import\\s*\\(|src=|href=|@import\\s*)[\\\"']?[^\\n]*?/experience/${sibling}/`,'i');assert.equal(pattern.test(source),false,`${path.relative(root,file)} imports Experience ${sibling}`)}});

test('PWA scopes, cache namespaces and client preferences are isolated',()=>{const m1=JSON.parse(read('public/experience/1/manifest.webmanifest'));const m2=JSON.parse(read('public/experience/2/manifest.webmanifest'));assert.equal(m1.scope,'/experience/1/');assert.equal(m1.start_url,'/experience/1/');assert.equal(m2.scope,'/experience/2/');assert.equal(m2.start_url,'/experience/2/');assert.notEqual(m1.scope,m2.scope);const sw1=read('public/experience/1/sw.js'),sw2=read('public/experience/2/sw.js');assert.match(sw1,/growth-compass-preview2-e1-/);assert.match(sw2,/growth-compass-preview2-e2-/);assert.doesNotMatch(sw1,/growth-compass-preview2-e2-/);assert.doesNotMatch(sw2,/growth-compass-preview2-e1-/);assert.match(read('public/experience/1/bootstrap.js'),/growth-compass:/);assert.match(read('public/experience/2/js/core/preferences.js'),/growth-compass:preview2:e2:/);});
