import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';

const branchGate=await readFile(new URL('../.github/workflows/deploy-preview2-branch.yml',import.meta.url),'utf8');
const quality=await readFile(new URL('../.github/workflows/quality.yml',import.meta.url),'utf8');
const remoteSmoke=await readFile(new URL('../.github/workflows/preview2-remote-smoke.yml',import.meta.url),'utf8');
const bootstrap=await readFile(new URL('../docs/PREVIEW2_BOOTSTRAP.md',import.meta.url),'utf8');
const authRollout=await readFile(new URL('../docs/PREVIEW2_INTERNAL_AUTH_ROLLOUT.md',import.meta.url),'utf8');
const startHere=await readFile(new URL('../START_PREVIEW2_CHAT.md',import.meta.url),'utf8');
const CHECKOUT_SHA='d23441a48e516b6c34aea4fa41551a30e30af803';
const AUTH_MIGRATION_BLOB='c902d52f0a5d33bda61df5cc59f50d11c0627792';
const TIME_AWARE_MIGRATION_BLOB='9c5866c1868c788430a7954ce8b15c4a558d99c0';
const JOURNAL_ARCHIVE_MIGRATION_BLOB='7fb5c2588b4dc0097e853f0780827c6dac370908';
const CANONICAL_PREVIEW2_ORIGIN='https://personal-growth-tracker-preview2.m-nejatmand.workers.dev';

test('Preview 2 branch workflow is a non-deploying gate pinned to the dedicated branch',()=>{assert.match(branchGate,/branches: \[feature\/experience-v2\]/);assert.match(branchGate,/github\.ref == 'refs\/heads\/feature\/experience-v2'/);assert.match(branchGate,new RegExp(`actions/checkout@${CHECKOUT_SHA}`));assert.match(branchGate,/persist-credentials: false/);assert.match(branchGate,/Deployment is intentionally delegated to the Quality PR workflow/);assert.doesNotMatch(branchGate,/CLOUDFLARE_API_TOKEN|CLOUDFLARE_ACCOUNT_ID|wrangler|d1 migrations|\/d1\/database|workers\/scripts/);});
test('successful Quality is the sole exact-head isolated Preview 2 deployment authority',()=>{assert.match(quality,/deploy-preview2:/);assert.match(quality,/needs: test/);assert.match(quality,/github\.event_name == 'pull_request'/);assert.match(quality,/github\.event\.pull_request\.head\.ref == 'feature\/experience-v2'/);assert.match(quality,/ref: \$\{\{ github\.event\.pull_request\.head\.sha \}\}/);assert.match(quality,/test "\$\(git rev-parse HEAD\)" = "\$TESTED_SHA"/);assert.match(quality,/personal-growth-tracker-preview2/);assert.match(quality,/Preview 2 points at Production D1\. Refusing deployment\./);assert.match(quality,/Preview 2 points at Preview 1 D1\. Refusing deployment\./);assert.match(quality,/--env preview2 --config \.wrangler\.preview2\.json --name personal-growth-tracker-preview2 --message "git:\$TESTED_SHA"/);});
test('Quality captures named rollback identity and D1 Time Travel before any migration or deploy',()=>{const capture=quality.indexOf('Capture current Preview 2 rollback identity and D1 bookmark');const migrate=quality.indexOf('Apply only the explicitly authorized Preview 2 migration set');const deploy=quality.indexOf('Deploy exact tested Preview 2 Worker only');assert.ok(capture>=0&&capture<migrate&&migrate<deploy);assert.match(quality,/BACKUP_KEY: preview2-ambient-luxury-2026-08-22/);assert.match(quality,/\/workers\/scripts\/\$\{worker\}\/deployments/);assert.match(quality,/\/d1\/database\/\$\{dbId\}\/time_travel\/bookmark/);assert.match(quality,/worker_message/);assert.match(quality,/worker_version_ids/);assert.match(quality,/d1_time_travel_bookmark/);assert.match(quality,/retention-days: 90/);});
test('Quality authorizes only the exact guarded migration set and rechecks pending state',()=>{assert.match(quality,/authorized_count='10'/);assert.match(quality,new RegExp(`verify_blob '0008_auth_multi_user\\.sql' '${AUTH_MIGRATION_BLOB}'`));assert.match(quality,new RegExp(`verify_blob '0009_time_aware_capacity\\.sql' '${TIME_AWARE_MIGRATION_BLOB}'`));assert.match(quality,new RegExp(`verify_blob '0010_journal_archive\\.sql' '${JOURNAL_ARCHIVE_MIGRATION_BLOB}'`));assert.match(quality,/GC_PREVIEW2_MIGRATION_CONFIRM: personal-growth-tracker-preview2/);assert.match(quality,/bash scripts\/migrate-preview2\.sh/);assert.match(quality,/Verify no pending Preview 2 migrations before deploy/);assert.match(quality,/No migrations to apply/);});
test('Quality verifies exact deployed head and real isolated Preview 2 D1 JSON',()=>{assert.match(quality,/deployment message mismatch/);assert.match(quality,/serialized\.includes\('\"quick_check\":\"ok\"'\)/);assert.match(quality,/serialized\.includes\('\"status\":\"ok\"'\)/);assert.match(quality,/\/d1\/database\?per_page=1000/);assert.match(quality,/Preview 2 D1 overlaps Preview 1 or Production/);assert.match(quality,/PRAGMA quick_check; SELECT 'ok' AS status;/);assert.match(quality,/Exact tested Preview 2 deployment verified/);});
test('independent remote smoke proves the staged auth boundary and isolated resources',()=>{assert.match(remoteSmoke,/Verify staged auth boundary, exact Worker deployment and isolated D1 directly/);assert.match(remoteSmoke,/Preview 2 is publicly reachable/);assert.match(remoteSmoke,/Anonymous Preview 2 is blocked by Cloudflare Access as expected/);assert.match(remoteSmoke,/Growth Compass internal authentication is enforcing the public\/private boundary/);assert.match(remoteSmoke,/\/workers\/scripts\/\$\{worker\}\/subdomain/);assert.match(remoteSmoke,/\/d1\/database\?per_page=1000/);assert.match(remoteSmoke,/Preview 2 D1 overlaps Preview 1 or Production/);assert.doesNotMatch(remoteSmoke,/CF_ACCESS_CLIENT_ID|CF_ACCESS_CLIENT_SECRET|CF-Access-Client-Id|CF-Access-Client-Secret/);});
test('Preview 2 operational docs agree on the canonical auth origin',()=>{for(const document of [bootstrap,authRollout,startHere]){assert.match(document,new RegExp(CANONICAL_PREVIEW2_ORIGIN.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.doesNotMatch(document,/feature-experience-v2-personal-growth-tracker\.m-nejatmand\.workers\.dev/);}assert.match(authRollout,/BETTER_AUTH_URL/);assert.match(authRollout,/Cloudflare Git-generated commit and branch preview hostnames/);});
test('Preview 2 operational docs retain migration and auth activation controls',()=>{assert.match(bootstrap,/exactly ten SQL migration files/);assert.match(bootstrap,/guarded idempotent Preview 2 migration script/);assert.match(startHere,/GC_PREVIEW2_INTERNAL_AUTH_ENABLED=true/);assert.doesNotMatch(startHere,/GC_PREVIEW2_ENABLED=true/);assert.match(authRollout,/store \*\*all Growth Compass auth runtime bindings as Preview 2 Worker secrets\*\*/);assert.match(authRollout,/GC_AUTH_MODE=enforced/);assert.match(authRollout,/Cloudflare Access is \*\*still present\*\*/);});